import os
import json
from dotenv import load_dotenv
from typing_extensions import TypedDict
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage
from langgraph.graph import StateGraph, END

# Load API keys from .env file securely
load_dotenv()

# 1. Define the Graph State
class AgentState(TypedDict):
    topic: str
    timeline_json: str

# 2. Node: The AI Planner
def planner_node(state: AgentState):
    print(f"-> Node: Planner running for topic: '{state['topic']}'")
    
    # DeepSeek operates on the OpenAI client standard
    llm = ChatOpenAI(
        api_key=os.environ.get("DEEPSEEK_API_KEY"),
        base_url="https://api.deepseek.com",
        model="deepseek-chat",
        max_tokens=1000
    )
    
    # Strict prompt engineering to prevent JSON hallucinations
    prompt = f"""
    You are the Director Agent for a documentary automation system.
    The topic is "{state['topic']}".
    
    Output ONLY a raw, valid JSON object representing the video timeline. 
    You must use the dummy cache files provided below for this test run.
    Do NOT include markdown formatting like ```json.
    
    Exact Schema Required:
    {{
      "render_settings": {{"resolution": [1920, 1080], "fps": 30}},
      "audio_timeline": [
        {{"track": "voice", "file": "cache/audio/test_audio.wav", "start_time": 0.0, "end_time": 5.0}}
      ],
      "video_timeline": [
        {{"layer": 1, "file": "cache/video/test_clip.mp4", "start_time": 0.0, "end_time": 5.0, "transition_out": "none"}}
      ]
    }}
    """
    
    response = llm.invoke([HumanMessage(content=prompt)])
    
    # Strip any accidental markdown formatting from DeepSeek's response
    clean_json = response.content.replace("```json", "").replace("```", "").strip()
    return {"timeline_json": clean_json}

# 3. Node: The File Writer
def writer_node(state: AgentState):
    print("-> Node: Writing timeline.json contract to disk...")
    with open("timeline.json", "w") as f:
        f.write(state["timeline_json"])
    return state

# 4. Compile the Graph
workflow = StateGraph(AgentState)
workflow.add_node("planner", planner_node)
workflow.add_node("writer", writer_node)

workflow.set_entry_point("planner")
workflow.add_edge("planner", "writer")
workflow.add_edge("writer", END)

app = workflow.compile()

if __name__ == "__main__":
    if not os.environ.get("DEEPSEEK_API_KEY"):
        print("CRITICAL ERROR: DEEPSEEK_API_KEY not found in .env")
        exit(1)
        
    print("Initializing AI Orchestrator...")
    # Execute the graph for a test topic
    final_state = app.invoke({"topic": "The Fermi Paradox"})
    print("LangGraph execution complete. timeline.json generated by DeepSeek.")
