"""Publishing metadata generation for the OpenClaw Video Engine.

Deterministic, rule-based metadata (no LLM calls, no randomness) derived from
a run's artifacts — ``beatsheet.json``, ``shotlist.json``, ``visualspec.json``,
``qareport.json`` — plus the topic. Produces YouTube-oriented publishing
fields: title candidates, description, tags, chapters and credits.

Usage::

    from engine.publishing import generate_metadata, save

    meta = generate_metadata("results/space_black_engine", topic="Why does space look black?")
    save(meta, "results/space_black_engine")          # writes metadata.json
"""

from __future__ import annotations

import json
import os
import re
from typing import Any, Dict, List, Optional, Sequence

SCHEMA = "publishing_metadata_v1"
ATTRIBUTION = "Generated by the OpenClaw Video Engine"
MAX_TITLE_CHARS = 60
MAX_CHAPTER_TITLE_CHARS = 45

# Words that carry no topical signal; ignored by keyword extraction.
_STOPWORDS = frozenset(
    """
    a an the and or but if then else when while what why how who whom which
    this that these those it its is are was were be been being do does did
    have has had not no nor of in on at to for with from by as into over under
    about against between through during before after above below up down out
    off again further once here there all any both each few more most other
    some such only own same so than too very can will just should now let
    keep keeps keep_ lets let's s t don't doesnt won't well really way
    never always without every still even maybe often thing things
    """.split()
)

# Generic math/science tag pool used to pad tags to the 6-10 band.
_TAG_POOL = [
    "science",
    "math",
    "animation",
    "explainer",
    "education",
    "motion graphics",
    "visualization",
    "stem",
    "learning",
    "documentary",
]


# ────────────────────────────────────────────────────────────────────────────
# Artifact loading
# ────────────────────────────────────────────────────────────────────────────

def _read_json(path: str) -> Optional[Dict[str, Any]]:
    """Return parsed JSON from ``path``, or ``None`` when unreadable."""
    try:
        with open(path, "r", encoding="utf-8") as fh:
            data = json.load(fh)
        return data if isinstance(data, dict) else None
    except (OSError, ValueError):
        return None


def _load_run_artifacts(run_dir: str) -> Dict[str, Optional[Dict[str, Any]]]:
    """Load the four canonical artifacts from a run directory.

    Missing/unparseable artifacts become ``None`` — metadata generation is
    tolerant of incomplete runs and only uses what is actually present.
    """
    return {
        "beatsheet": _read_json(os.path.join(run_dir, "beatsheet.json")),
        "shotlist": _read_json(os.path.join(run_dir, "shotlist.json")),
        "visualspec": _read_json(os.path.join(run_dir, "visualspec.json")),
        "qareport": _read_json(os.path.join(run_dir, "qareport.json")),
    }


# ────────────────────────────────────────────────────────────────────────────
# Text helpers (all deterministic)
# ────────────────────────────────────────────────────────────────────────────

def _clean_title_text(text: str) -> str:
    """Make text YouTube-safe for a title: drop control chars and ``<>``,
    collapse whitespace, trim trailing sentence punctuation."""
    text = str(text or "")
    text = re.sub(r"[\x00-\x1f\x7f]", " ", text)          # control chars
    text = re.sub(r"[<>]", "", text)                      # not allowed in titles
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"[.!?]+$", "", text)                   # trim trailing punctuation
    return text.strip()


def _first_sentence(text: str) -> str:
    """First sentence of ``text`` (split on ``.`` ``!`` ``?``)."""
    text = (text or "").strip()
    if not text:
        return ""
    parts = re.split(r"(?<=[.!?])\s+", text)
    return parts[0].strip()


def _truncate_words(text: str, max_len: int) -> str:
    """Truncate ``text`` at a word boundary to at most ``max_len`` chars."""
    text = (text or "").strip()
    if len(text) <= max_len:
        return text
    words = text.split()
    out: List[str] = []
    for word in words:
        if len(" ".join(out + [word])) <= max_len:
            out.append(word)
        else:
            break
    if out:
        return " ".join(out)
    return text[: max_len - 1] + "…"


def _join_pair(left: str, sep: str, right: str, max_len: int) -> str:
    """Join ``left`` + ``sep`` + ``right`` within ``max_len``.

    Only composes the pair when BOTH sides fit whole; otherwise returns
    the left side alone (word-boundary truncated).  This kills the
    naive-concatenation artifact class where a long topic squeezed the
    hook down to a mid-word fragment ("…paint: This", "…— Th…" —
    the truncated Gabriel's Horn titles, 2026-08-27).
    """
    left = _clean_title_text(left)
    right = _clean_title_text(right)
    if not left:
        return _truncate_words(right, max_len)
    if not right:
        return _truncate_words(left, max_len)
    if len(left) + len(sep) + len(right) <= max_len:
        return f"{left}{sep}{right}"
    return _truncate_words(left, max_len)


def _key_narration_phrase(beats: Sequence[Dict[str, Any]]) -> str:
    """Short hook phrase: first sentence of the first ``hook``-intent beat's
    narration (falling back to the first beat)."""
    if not beats:
        return ""
    beat = next((b for b in beats if b.get("intent") == "hook"), beats[0])
    sentence = _first_sentence(beat.get("narration", ""))
    # Prefer the first clause when the full sentence is unwieldy.
    if len(sentence) > 56:
        clause = re.split(r"[,;—–]", sentence)[0].strip()
        if len(clause) > 8:
            sentence = clause
    return sentence


# ────────────────────────────────────────────────────────────────────────────
# Field builders
# ────────────────────────────────────────────────────────────────────────────

def _title_candidates(topic: str, phrase: str) -> List[str]:
    """Three clean title candidates, each <= 60 chars (YouTube title sweet
    spot), each a complete readable phrase — never a truncated
    topic+hook concatenation:

    1. the hook, standalone (a complete claim)
    2. topic name (text before ':') + hook, when both fit whole
    3. hook clause | topic name, when both fit whole

    Every variant is word-boundary clean and <= MAX_TITLE_CHARS.
    """
    t = _clean_title_text(topic)
    p = _clean_title_text(phrase)
    if not t:
        t = "Untitled video"
    if not p:
        p = t
    # Topic short name: the part before the first colon — a real title
    # usually names the object ("Gabriel's Horn"), not the full topic
    # sentence.
    name = t.split(":")[0].strip() or t
    clause = p
    if len(p) > 40:
        first = re.split(r"[—–;,]", p)[0].strip()
        if len(first) >= 12:
            clause = first
    candidates = [
        _truncate_words(p, MAX_TITLE_CHARS),
        max((_join_pair(name, ": ", p, MAX_TITLE_CHARS),
             _join_pair(name, ": ", clause, MAX_TITLE_CHARS)), key=len),
        _join_pair(clause, " | ", name, MAX_TITLE_CHARS),
    ]
    # Deduplicate while preserving order; pad from the topic when a
    # variant collapsed onto another so three distinct options remain.
    seen: set = set()
    unique = []
    for c in candidates:
        key = c.lower()
        if c and key not in seen:
            seen.add(key)
            unique.append(c)
    for fallback in (_truncate_words(t, MAX_TITLE_CHARS),
                     _truncate_words(name, MAX_TITLE_CHARS)):
        if len(unique) >= 3:
            break
        if fallback and fallback.lower() not in seen:
            seen.add(fallback.lower())
            unique.append(fallback)
    # Last resort when topic and hook are too entangled for whole-phrase
    # pairs: a word-boundary-truncated hook after the topic name (still
    # never a mid-word cut, and only when at least 4 words survive).
    while len(unique) < 3:
        budget = MAX_TITLE_CHARS - len(name) - 3
        trimmed = _truncate_words(p, max(budget, 0))
        if (not trimmed or len(trimmed.split()) < 4
                or f"{name} | {trimmed}".lower() in seen):
            break
        cand = f"{name} | {trimmed}"
        seen.add(cand.lower())
        unique.append(cand)
    return unique or [_truncate_words(t, MAX_TITLE_CHARS)]


def _keyword_terms(beats: Sequence[Dict[str, Any]], limit: int = 4) -> List[str]:
    """Most frequent topical words across all narration (deterministic)."""
    counts: Dict[str, int] = {}
    for beat in beats:
        text = (beat.get("narration") or "").lower()
        for word in re.findall(r"[a-z][a-z0-9'-]{2,}", text):
            if word not in _STOPWORDS and not word.isdigit():
                counts[word] = counts.get(word, 0) + 1
    ranked = sorted(counts.items(), key=lambda kv: (-kv[1], kv[0]))
    return [w for w, _ in ranked[:limit]]


def _description(
    topic: str,
    phrase: str,
    beats: Sequence[Dict[str, Any]],
    duration: Optional[float],
    qa_passed: Optional[bool],
) -> str:
    """2-3 factual, keyword-rich sentences. No hallucinated claims: every
    number comes from the artifacts."""
    t = _clean_title_text(topic).lower() or "this topic"
    sentences = [f"An animated explainer about {t}."]
    if phrase:
        sentences.append(f"The video opens with: “{phrase.rstrip('.!?')}.”")
    terms = _keyword_terms(beats, limit=3)
    if terms:
        sentences.append(f"Key terms covered: {', '.join(terms)}.")
    if duration is not None:
        mins = duration / 60.0
        runtime = f"about {duration:.0f} seconds" if mins < 1 else f"about {mins:.1f} minutes"
        chapter_count = len(_chapters(beats))
        qa_note = " and it passed automated quality review" if qa_passed else ""
        sentences.append(f"Runtime {runtime} across {chapter_count} chapters{qa_note}.")
    return " ".join(sentences)


def _topic_tags(topic: str) -> List[str]:
    """Topical tags: meaningful words of the topic, plus the whole topic when
    short. Deterministic order."""
    cleaned = _clean_title_text(topic)
    if not cleaned:
        return []
    tags: List[str] = []
    full = cleaned.lower()
    if len(full) <= 30:
        tags.append(full)
    for word in re.findall(r"[a-z][a-z0-9'-]{2,}", full):
        if word not in _STOPWORDS and word not in tags:
            tags.append(word)
        if len(tags) >= 3:
            break
    return tags


def _tags(topic: str) -> List[str]:
    """6-10 tags: topical + math/science, deduplicated, lowercase."""
    tags: List[str] = []
    for tag in _topic_tags(topic) + _TAG_POOL:
        tag = tag.strip().lower()
        if tag and tag not in tags:
            tags.append(tag)
        if len(tags) >= 10:
            break
    return tags


def _chapters(beats: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Chapters from beatsheet beats: ``[{start, title}]``.

    Skips beats without narration, truncates titles, and merges consecutive
    beats that would produce identical chapter titles.
    """
    chapters: List[Dict[str, Any]] = []
    for beat in beats:
        title = _clean_title_text(beat.get("narration", ""))
        if not title:
            continue
        title = _truncate_words(title, MAX_CHAPTER_TITLE_CHARS)
        start = round(float(beat.get("start", 0.0)), 1)
        if chapters and chapters[-1]["title"] == title:
            continue  # absorb into previous chapter
        chapters.append({"start": start, "title": title})
    return chapters


def _duration(beatsheet: Optional[Dict[str, Any]], beats: Sequence[Dict[str, Any]]) -> Optional[float]:
    """Video duration from artifact metadata, else last beat end."""
    if beatsheet:
        meta = beatsheet.get("metadata") or {}
        if isinstance(meta.get("duration"), (int, float)):
            return round(float(meta["duration"]), 1)
    if beats:
        ends = [float(b.get("end", 0.0)) for b in beats]
        return round(max(ends), 1)
    return None


# ────────────────────────────────────────────────────────────────────────────
# Public API
# ────────────────────────────────────────────────────────────────────────────

def generate_metadata(
    run_dir: Optional[str] = None,
    topic: Optional[str] = None,
    beatsheet: Optional[Dict[str, Any]] = None,
    shotlist: Optional[Dict[str, Any]] = None,
    visualspec: Optional[Dict[str, Any]] = None,
    qareport: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """Produce a publishing metadata dict from run artifacts.

    ``run_dir`` points at a ``results/<run>`` directory containing the four
    canonical artifacts; any of the artifact dicts may also be passed
    directly. All fields are deterministic (no LLM). Returns a plain dict.
    """
    if run_dir is None and not any((beatsheet, shotlist, visualspec, qareport, topic)):
        raise ValueError("generate_metadata needs a run_dir or at least one artifact")

    loaded = _load_run_artifacts(run_dir) if run_dir else {}
    beatsheet = beatsheet if beatsheet is not None else loaded.get("beatsheet")
    shotlist = shotlist if shotlist is not None else loaded.get("shotlist")
    visualspec = visualspec if visualspec is not None else loaded.get("visualspec")
    qareport = qareport if qareport is not None else loaded.get("qareport")

    beats = list((beatsheet or {}).get("beats") or [])
    shots = list((shotlist or {}).get("shots") or [])

    # Topic resolution: explicit arg > beatsheet metadata > run dir name.
    if not topic and beatsheet:
        topic = (beatsheet.get("metadata") or {}).get("topic")
    if not topic and run_dir:
        topic = os.path.basename(os.path.normpath(run_dir)).replace("_", " ")
    topic = (topic or "").strip()

    phrase = _key_narration_phrase(beats)
    duration = _duration(beatsheet, beats)
    qa_passed = bool(qareport.get("passed")) if qareport else None
    chapters = _chapters(beats)
    title_candidates = _title_candidates(topic, phrase)

    credits = {
        "attribution": ATTRIBUTION,
        "engine": "OpenClaw Video Engine",
        "style_spec": (beatsheet or {}).get("version", "v1"),
        "schema": SCHEMA,
    }

    source = {
        "run_dir": os.path.normpath(run_dir) if run_dir else None,
        "artifacts": {
            "beatsheet": beatsheet is not None,
            "shotlist": shotlist is not None,
            "visualspec": visualspec is not None,
            "qareport": qareport is not None,
        },
        "topic": topic,
        "duration_seconds": duration,
        "beat_count": len(beats),
        "shot_count": len(shots),
        "qa_passed": qa_passed,
    }

    return {
        "schema": SCHEMA,
        "topic": topic,
        "title": title_candidates[0],
        "title_candidates": title_candidates,
        "description": _description(topic, phrase, beats, duration, qa_passed),
        "tags": _tags(topic),
        "chapters": chapters,
        "credits": credits,
        "source": source,
    }


def save(meta: Dict[str, Any], out_dir: str, filename: str = "metadata.json") -> str:
    """Write ``meta`` to ``out_dir/filename`` as pretty JSON.

    Adds a ``generated_at`` timestamp at write time (the metadata dict itself
    stays deterministic). Returns the output path.
    """
    import datetime

    os.makedirs(out_dir, exist_ok=True)
    payload = dict(meta)
    payload["generated_at"] = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    out_path = os.path.join(out_dir, filename)
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=2, ensure_ascii=False)
        fh.write("\n")
    return out_path
