"""VisualSpec -> Manim compiler (directive §4, §5, §49 Phase 5).

DeepSeek emits a strict JSON VisualSpec (WHAT/WHY/WHEN).  This deterministic
compiler is the ONLY bridge to Manim — it maps each transformation to a
trusted primitive.  DeepSeek never writes arbitrary Manim code as the
primary interface.

The compiler:
  1. Validates the VisualSpec against the schema (Gate 1).
  2. Verifies every mathematical value (Gate 3) before rendering.
  3. Emits a Manim Scene class per beat (incrementally renderable, §31).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from engine.primitives import manim_primitives as P
from engine.validation import math_verify as M
from engine.validation.schema import validate_visualspec


class CompileError(ValueError):
    """Raised when a VisualSpec cannot be compiled safely."""


# Transformation type -> primitive callable, plus a guard hook.
_TRANSFORM_MAP: dict[str, str] = {
    "sort": "DigitSort",
    "reverse": "DigitSort",
    "digit_permute": "DigitSort",
    "subtract": "KaprekarStep",
    "transform": "DigitMorph",
    "morph": "DigitMorph",
    "count_down": "ConvergenceParticles",
    "converge": "ConvergenceParticles",
    "orbital": "ConvergenceParticles",
    "reveal": "FixedPointReveal",
    "highlight": "KineticTypography",
}

_NARRATIVE_TYPES = {
    "QuestionReveal": "QuestionReveal",
    "ClaimReveal": "ClaimReveal",
    "Comparison": "Comparison",
    "CycleReveal": "CycleReveal",
}


def _math_guard(beat: dict) -> None:
    """Deterministic math verification for a beat's transformations."""
    intent = beat.get("intent", "")
    for tf in beat.get("transformations", []):
        t = tf.get("type")
        if t in ("sort", "reverse", "digit_permute") and "from" in tf and "to" in tf:
            ret = M._digits_ok(str(tf["to"]), len(str(tf["to"])))
            if ret:
                raise CompileError(f"bad digit target: {ret}")
        if t == "subtract":
            frm = str(tf.get("from", "")).zfill(4)
            to = str(tf.get("to", "")).zfill(4)
            v = M.verify_kaprekar_step(to, 4, frm)
            if not v.ok:
                raise CompileError(
                    f"math verification failed for {intent}: "
                    + "; ".join(f["detail"] for f in v.failures())
                )


def compile_beat(beat: dict) -> list[str]:
    """Return a list of Manim code statements (body) for one beat."""
    _math_guard(beat)
    stmts: list[str] = []
    for tf in beat.get("transformations", []):
        t = tf.get("type")
        prim = _TRANSFORM_MAP.get(t)
        if prim is None:
            raise CompileError(f"unmapped transformation: {t}")

        if prim == "KaprekarStep":
            frm = str(tf.get("from", "")).zfill(4)
            to = str(tf.get("to", "")).zfill(4)
            stmts.append(f"KaprekarStep(self, {frm!r}, {to!r}, ndigits=4)")
        elif prim in ("DigitSort", "DigitMorph"):
            pass  # handled below with concrete value
        elif prim == "ConvergenceParticles":
            target = tf.get("to", "6174")
            stmts.append(
                f"t = Text({target!r}, font=STYLE_FONT, font_size=STYLE_DIGIT, "
                f"color=ACCENT0); self.add(t); "
                f"ConvergenceParticles(self, t, n=40, duration=1.8)"
            )
        elif prim == "FixedPointReveal":
            stmts.append(f"FixedPointReveal(self, {str(tf.get('to', '6174'))!r})")
        elif prim == "KineticTypography":
            word = tf.get("to") or tf.get("from") or "!"
            stmts.append(f"KineticTypography(self, {word!r})")

    # narrative primitives directly named in intent
    for kind, fn in _NARRATIVE_TYPES.items():
        if kind.lower() in beat.get("intent", "").lower():
            text = beat.get("narration", "")
            stmts.append(f"{fn}(self, {text!r})")

    if not stmts:
        stmts.append("# (no-op beat — narration-only pause)")
    return stmts


def emit_scene(vs: dict, scene_name: str = "BenchScene") -> str:
    """Compile a full VisualSpec into a standalone Manim Scene source string.

    Returns source that Manim can render via:
        manim render --format=mp4 <scene.py> <SceneName>
    """
    errs = validate_visualspec(vs)
    if errs:
        raise CompileError("VisualSpec failed schema validation:\n" + "\n".join(errs))

    body: list[str] = []
    for beat in vs["beats"]:
        bid = beat["beat_id"]
        body.append(f"        # ---- beat {bid}: {beat.get('intent','')} ----")
        body.extend("        " + s for s in compile_beat(beat))
        dur = beat.get("duration", 1.0)
        body.append(f"        self.wait({dur:.2f})")

    source = f'''"""
Auto-generated by the VisualSpec compiler.  Deterministic; do not hand-edit.
"""
import os
import sys

# Ensure the video_engine repo root (ancestor containing the engine/ package)
# is importable regardless of Manim's working directory.
_REPO = os.path.dirname(os.path.abspath(__file__))
while _REPO and not os.path.isdir(os.path.join(_REPO, "engine")):
    _parent = os.path.dirname(_REPO)
    if _parent == _REPO:
        break
    _REPO = _parent
if os.path.isdir(os.path.join(_REPO, "engine")) and _REPO not in sys.path:
    sys.path.insert(0, _REPO)

from manim import Scene, Text
from engine.primitives.manim_primitives import (
    KaprekarStep, DigitSort, DigitMorph, AttractorOrbit, FixedPointReveal,
    ConvergenceParticles, QuestionReveal, ClaimReveal, KineticTypography,
    Comparison, CycleReveal,
)
from engine.config.loader import get_style

_STYLE = get_style()
STYLE_FONT = _STYLE.get("font_family", "DejaVu Sans")
STYLE_DIGIT = _STYLE.get("font_sizes", {{}}).get("digit", 64)
ACCENT0 = _STYLE.get("accent_colors", ["#4FC3F7"])[0]


class {scene_name}(Scene):
    def construct(self):
{chr(10).join(body)}
'''

    return source


def compile_to_file(vs: dict, out_path: str | Path, scene_name: str = "BenchScene") -> Path:
    """Compile VisualSpec to a .py scene file on disk (for incremental render)."""
    out = Path(out_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(emit_scene(vs, scene_name), encoding="utf-8")
    return out


if __name__ == "__main__":
    demo = {
        "version": "v1",
        "beats": [
            {
                "beat_id": "b001",
                "intent": "hook",
                "narration": "Try this number trick.",
                "duration": 1.5,
                "objects": [{"id": "number_main", "type": "number"}],
                "transformations": [
                    {"type": "highlight", "from": "3524", "to": "3524", "params": {}}
                ],
            },
            {
                "beat_id": "b002",
                "intent": "demonstrate_transformation",
                "narration": "Now reverse the digits.",
                "duration": 1.8,
                "objects": [{"id": "number_main", "type": "number"}],
                "transformations": [
                    {"type": "subtract", "from": "3524", "to": "3087", "params": {}}
                ],
            },
        ],
    }
    src = emit_scene(demo)
    print(src[:1200])
