#!/usr/bin/env python3
"""ice_slippery V13 card manifest — realigned to the 6-beat visual plan.

V13 plates are generated by make_plates.py (deterministic ink-wash cards,
no baked-in text). This file no longer draws a parallel V6 card set: its
job is the plate-element manifest the planner parses (engine.planv5.
_plate_manifest) — per-asset label anchors at TRUE plate-feature
coordinates, feeding hero recognizability, planv8 state choreography
(REVEAL/ISOLATE/FLOW/CONSEQUENCE rects) and the v9 contradiction/payoff
localization.

Coordinate convention: the manifest parser reads positions as fractions of
a 1536x1024 stage (cx/1536, cy/1024). The V13 plates are 2160x3840, so
every coordinate below is plate_px * (1536/2160, 1024/3840) — i.e.
(x*0.71111, y*0.26667) — taken from the card_bN() geometry in
make_plates.py. Running this script delegates to make_plates.py so the
committed plate set stays the single source of pixels.
"""
from pathlib import Path
import sys

HERE = Path(__file__).resolve().parent


# ── manifest functions (parsed for label() anchors; never drawn) ─────────

def is_b1_ice_macro():
    # facets field ~ (1000,1300); rust glow at (1350,1750); lower glow (700,2900)
    label(d, "ICE FACETS", (711, 347))
    label(d, "GLINTING SHEEN", (960, 467))
    label(d, "FROZEN SURFACE", (498, 773))


def is_b2_pressure_micro():
    # blade shaft (1080,1700); rust wedge (1080,2050); droplets (1080,2500); slab (1560,2950)
    label(d, "SKATE BLADE", (768, 453))
    label(d, "PRESSURE WEDGE", (768, 547))
    label(d, "MELTWATER", (768, 667))
    label(d, "ICE SLAB", (1109, 787))


def is_b3_lattice():
    # top of outer ring (1080,1080); r660 vertex (1740,1980); center (1080,1980)
    label(d, "HEXAGONAL RING", (768, 288))
    label(d, "FOUR BONDS", (1237, 528))
    label(d, "GLOWING CENTER", (768, 528))


def is_b4_water_film():
    # film band (1080,1530); loose molecules (1080,1900); lattice rows (1080,2900)
    label(d, "LIQUID FILM", (768, 408))
    label(d, "BROKEN BONDS", (768, 507))
    label(d, "ICE LATTICE", (768, 773))


def is_b5_glide():
    # blade contact (1300,2000); film line left (700,2160); spray arcs (1560,1980)
    label(d, "BLADE EDGE", (924, 533))
    label(d, "WATER FILM", (498, 576))
    label(d, "SPRAY ARCS", (1110, 528))


def is_b6_payoff():
    # film band (1080,1875); lattice rings center (1080,2680)
    label(d, "LIQUID SKIN", (768, 500))
    label(d, "SOLID LATTICE", (768, 715))


# asset id -> manifest function (parser contract: quoted asset id maps to
# a zero-arg function call)
PLATES = {
    "IS_B1_ice_macro": is_b1_ice_macro(),
    "IS_B2_pressure_micro": is_b2_pressure_micro(),
    "IS_B3_lattice": is_b3_lattice(),
    "IS_B4_water_film": is_b4_water_film(),
    "IS_B5_glide": is_b5_glide(),
    "IS_B6_payoff": is_b6_payoff(),
}


def main() -> int:
    """Delegate plate generation to the V13 generator (single pixel source)."""
    import runpy
    sys.path.insert(0, str(HERE))
    runpy.run_path(str(HERE / "make_plates.py"), run_name="__main__")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
