#!/usr/bin/env python3
"""
review_video_multi.py — Cross-provider video review (Grok + DeepSeek pro).

Grok review: sends extracted frames + script to x-ai/grok-4.5 via OpenRouter
(vision-capable) and gets a structured review of the ACTUAL video.

DeepSeek pro review: DeepSeek is text-only, so it receives a "visual
transcript" (per-frame descriptions generated by Grok) + script + shot
timeline, and produces the same structured review schema.

Usage:
    python3 tools/review_video_multi.py --video results/.../mixed.mp4 \
        --frames tmp/review_frames --script script_final.json \
        --timeline timeline.json --outdir results/... --providers grok,deepseek
"""

import argparse
import base64
import json
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)) + "/..")
from dotenv import load_dotenv
load_dotenv(override=True)  # runtime injects a placeholder DEEPSEEK_API_KEY; .env has the real one

REVIEW_PROMPT = """You are the executive producer of a world-class documentary studio.
Review this rendered documentary video END-TO-END. You are shown sampled frames
from the video at their timestamps, plus the narration script. Evaluate:

1. factual accuracy (compare against the script claims provided)
2. narration quality (delivery, clarity, pronunciation)
3. script effectiveness (hook, structure, curiosity, pacing)
4. audience engagement & retention
5. visual relevance (do visuals match narration?)
6. visual continuity (style consistency across shots)
7. transitions and timing
8. cinematography & animation quality (motion, Ken Burns, Manim segments)
9. music balance (does music overwhelm narration?)
10. subtitle quality (if present)
11. thumbnail recommendation (a concrete frame description + timestamp)
12. title recommendation (3 options)

Respond in STRICT JSON (no markdown fences) with this schema:
{{
  "quality_score": <int 0-100>,
  "confidence": <float 0-1>,
  "strengths": ["..."],
  "weaknesses": ["..."],
  "prioritized_recommendations": [
    {{"priority": "critical|high|medium|low",
      "category": "pacing|transitions|music|audio_balance|color|subtitles|shot_order|zoom|story_change|fact_change|script_change|new_scene|new_asset|thumbnail|other",
      "recommendation": "<specific, actionable, parameter-level where possible>"}}
  ],
  "factual_issues": [{{"claim": "...", "issue": "...", "suggested_fix": "..."}}],
  "title_recommendations": ["t1", "t2", "t3"],
  "thumbnail_recommendation": "{{"timestamp": "<mm:ss>", "description": "..."}}",
  "overall_assessment": "<2-3 sentences>"
}}

SCRIPT (scene index: narration):
{script}

ATOMIC RUBRIC CHECKS (v12): sample the video at these exact timestamps and
answer each as a strict boolean. Timecodes are relative to video start; if a
timestamp exceeds video length, answer null.
{{
  "atomic_rubrics": [
    {{"t": "0:03", "check": "a single clear visual subject is visible", "pass": true}},
    {{"t": "0:15", "check": "the visual matches the narration playing at that moment", "pass": true}},
    {{"t": "0:30", "check": "there is camera motion or an animated element (not a frozen frame)", "pass": true}},
    {{"t": "0:45", "check": "no jarring cut or black frame", "pass": true}},
    {{"t": "1:00", "check": "narration is audible and not clipped mid-sentence", "pass": true}},
    {{"t": "1:30", "check": "visual style is consistent with the rest of the video", "pass": true}},
    {{"t": "1:45", "check": "music does not overpower the voice", "pass": true}}
  ],
  "rubric_pass_rate": <float 0-1>
}}
Answer each rubric as pass: true/false (or null if out of range). Base the
holistic quality_score on the rubric outcomes plus your expert judgment.

Be specific. Reference timestamps where useful. Prioritize fixes by impact."""

FRAME_DESC_PROMPT = """You are a documentary video assistant. Below are sampled
frames from a rendered documentary video, each tagged with its timestamp (sec).
For EACH frame, write ONE concise sentence describing what is visually shown:
subject, style (photorealistic render / animation / diagram / stock), colors,
any text/UI elements, and whether it looks like a real photograph, a CGI
render, a flat illustration, or a data diagram. Also flag anything that looks
like an artifact (mirrored edges, smearing, black frames, letterbox bars).
Output STRICT JSON (no fences): {{"frames": [{{"t": <sec>, "desc": "..."}}]}}
"""


def _load_script(path):
    with open(path) as f:
        data = json.load(f)
    if isinstance(data, dict):
        data = data.get("scenes") or data.get("final_scenes") or []
    lines = []
    for i, s in enumerate(data):
        if isinstance(s, dict):
            n = s.get("narration", "")
            lines.append(f"SCENE {i} [{s.get('title','')}]: {n}")
        else:
            lines.append(f"SCENE {i}: {s}")
    return "\n".join(lines)


def _load_timeline(path):
    if not path or not os.path.exists(path):
        return ""
    with open(path) as f:
        d = json.load(f)
    vt = d.get("video_timeline", [])
    if not isinstance(vt, list):
        return ""
    rows = []
    for s in vt:
        rows.append(
            f"{s.get('start_time',0):.1f}-{s.get('end_time',0):.1f}s "
            f"scene{s.get('scene_id')} [{s.get('shot_type')}] "
            f"{s.get('asset_source')} '{s.get('asset_title','')}' "
            f"cam={s.get('camera_move','')} q='{s.get('query_used','')}'"
        )
    return "\n".join(rows)


def _b64(path):
    with open(path, "rb") as f:
        return base64.b64encode(f.read()).decode()


def _openrouter_chat(messages, model, json_mode=True, max_tokens=3000,
                     base_url="https://openrouter.ai/api/v1/chat/completions",
                     attempts=8):
    """OpenAI-compatible chat via OpenRouter with Retry-After-aware backoff.

    OpenRouter free (:free) models 429 aggressively — honor Retry-After when
    present, else exponential backoff with jitter, up to ``attempts`` tries.
    """
    import urllib.request
    import urllib.error
    key = os.environ.get("OPENROUTER_API_KEY")
    body = {
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0.2,
    }
    if json_mode:
        body["response_format"] = {"type": "json_object"}
    headers = {
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
        "HTTP-Referer": "https://video-engine.local",
        "X-Title": "video-engine-review",
    }
    req = urllib.request.Request(
        base_url,
        data=json.dumps(body).encode(),
        headers=headers,
    )
    for attempt in range(attempts):
        try:
            with urllib.request.urlopen(req, timeout=900) as resp:
                data = json.loads(resp.read().decode())
            return data["choices"][0]["message"]["content"]
        except urllib.error.HTTPError as e:
            msg = str(e)
            print(f"  !! {model} attempt {attempt+1} failed: {msg[:150]}")
            retry_after = e.headers.get("Retry-After") if e.headers else None
            if e.code in (429, 500, 502, 503, 504, 529):
                if retry_after and retry_after.isdigit():
                    wait = int(retry_after) + 5
                else:
                    wait = 45 * (attempt + 1) + (attempt * 13)
                print(f"     retrying in {wait}s (Retry-After={retry_after})")
                time.sleep(wait)
                continue
            raise
        except Exception as e:
            msg = str(e)
            print(f"  !! {model} attempt {attempt+1} failed: {msg[:150]}")
            if "429" in msg or "5" in msg[:3]:
                time.sleep(45 * (attempt + 1))
                continue
            raise
    raise RuntimeError(f"{model}: all attempts failed")


def _nvidia_chat(messages, model, json_mode=True, max_tokens=3000, attempts=5):
    import urllib.request
    import urllib.error
    key = os.environ.get("NVIDIA_API_KEY")
    body = {
        "model": model,
        "messages": messages,
        "max_tokens": max_tokens,
        "temperature": 0.2,
    }
    if json_mode:
        body["response_format"] = {"type": "json_object"}
    req = urllib.request.Request(
        "https://integrate.api.nvidia.com/v1/chat/completions",
        data=json.dumps(body).encode(),
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
    )
    for attempt in range(attempts):
        try:
            with urllib.request.urlopen(req, timeout=900) as resp:
                data = json.loads(resp.read().decode())
            return data["choices"][0]["message"]["content"]
        except urllib.error.HTTPError as e:
            msg = str(e)
            print(f"  !! {model} attempt {attempt+1} failed: {msg[:150]}")
            retry_after = e.headers.get("Retry-After") if e.headers else None
            if e.code in (429, 500, 502, 503, 504):
                if retry_after and retry_after.isdigit():
                    wait = int(retry_after) + 5
                else:
                    wait = 20 * (attempt + 1)
                print(f"     retrying in {wait}s (Retry-After={retry_after})")
                time.sleep(wait)
                continue
            raise
        except Exception as e:
            msg = str(e)
            print(f"  !! {model} attempt {attempt+1} failed: {msg[:150]}")
            if "429" in msg or "5" in msg[:3]:
                time.sleep(20 * (attempt + 1))
                continue
            raise
    raise RuntimeError(f"{model}: all attempts failed")


def _openrouter_grok(messages, json_mode=True, max_tokens=3000):
    return _openrouter_chat(messages, "x-ai/grok-4.5", json_mode=json_mode, max_tokens=max_tokens)


def _deepseek_pro(prompt_text, max_tokens=4000):
    import urllib.request
    key = os.environ.get("DEEPSEEK_API_KEY")
    body = {
        "model": "deepseek-v4-pro",
        "messages": [
            {"role": "system", "content": "You are a rigorous documentary executive producer. Respond only in strict JSON."},
            {"role": "user", "content": prompt_text},
        ],
        "max_tokens": max_tokens,
        "temperature": 0.2,
        "response_format": {"type": "json_object"},
    }
    req = urllib.request.Request(
        "https://api.deepseek.com/chat/completions",
        data=json.dumps(body).encode(),
        headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"},
    )
    for attempt in range(5):
        try:
            with urllib.request.urlopen(req, timeout=600) as resp:
                data = json.loads(resp.read().decode())
            return data["choices"][0]["message"]["content"]
        except Exception as e:
            msg = str(e)
            print(f"  !! deepseek attempt {attempt+1} failed: {msg[:150]}")
            if "429" in msg or "5" in msg[:3] or "timeout" in msg.lower():
                time.sleep(20 * (attempt + 1))
                continue
            raise
    raise RuntimeError("deepseek: all attempts failed")


def _parse_json(text):
    text = text.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("json"):
            text = text[4:]
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start >= 0 and end > start:
            return json.loads(text[start:end + 1])
        raise RuntimeError(f"non-JSON output: {text[:300]}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--video", required=True)
    ap.add_argument("--frames", required=True, help="dir of f_XXX.jpg frames")
    ap.add_argument("--script", required=True)
    ap.add_argument("--timeline", default=None)
    ap.add_argument("--outdir", required=True)
    ap.add_argument("--providers", default="grok,deepseek")
    args = ap.parse_args()

    os.makedirs(args.outdir, exist_ok=True)
    script_text = _load_script(args.script)
    timeline_text = _load_timeline(args.timeline)
    frame_files = sorted(
        f for f in os.listdir(args.frames) if f.endswith(".jpg")
    )
    print(f"frames: {len(frame_files)} | script scenes: {script_text.count('SCENE')}")

    results = {}

    def _frames_content(prompt):
        content = [{"type": "text", "text": prompt}]
        for f in frame_files:
            content.append({
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{_b64(os.path.join(args.frames, f))}"},
            })
        return content

    if "gemma" in args.providers:
        # v19n: model fallback chain + per-provider isolation.  The 31b free
        # variant 429s hard on OpenRouter; fall back to the 26b free variant.
        gemma_models = [
            "google/gemma-4-31b-it:free",
            "google/gemma-4-26b-a4b-it:free",
        ]
        print("=== GEMMA 4 REVIEW (OpenRouter :free) ===")
        t0 = time.time()
        out = None
        used_model = None
        for gm in gemma_models:
            try:
                print(f"  trying {gm}")
                out = _openrouter_chat(
                    [{"role": "user", "content": _frames_content(REVIEW_PROMPT.format(script=script_text[:12000]))}],
                    gm,
                    attempts=6,
                )
                used_model = gm
                break
            except Exception as e:
                print(f"  !! {gm} gave up: {str(e)[:120]}")
        if out is None:
            print("  !! GEMMA: all free models exhausted — skipping (leaving any prior review_gemma.json)")
        else:
            review = _parse_json(out)
            review["_meta"] = {"provider": "gemma", "model": used_model, "elapsed_s": round(time.time() - t0, 1)}
            with open(os.path.join(args.outdir, "review_gemma.json"), "w") as f:
                json.dump(review, f, indent=2)
            results["gemma"] = review
            print(f"  score {review.get('quality_score')}/100 (conf {review.get('confidence')})")

    if "llama" in args.providers:
        print("=== LLAMA 3.2 90B VISION REVIEW (NVIDIA NIM) ===")
        t0 = time.time()
        try:
            out = _nvidia_chat(
                [{"role": "user", "content": _frames_content(REVIEW_PROMPT.format(script=script_text[:12000]))}],
                "meta/llama-3.2-90b-vision-instruct",
                attempts=6,
            )
        except Exception as e:
            print(f"  !! LLAMA failed: {str(e)[:150]} — skipping")
            out = None
        if out is not None:
            review = _parse_json(out)
            review["_meta"] = {"provider": "llama", "model": "meta/llama-3.2-90b-vision-instruct", "elapsed_s": round(time.time() - t0, 1)}
            with open(os.path.join(args.outdir, "review_llama.json"), "w") as f:
                json.dump(review, f, indent=2)
            results["llama"] = review
            print(f"  score {review.get('quality_score')}/100 (conf {review.get('confidence')})")

    if "gemini" in args.providers:
        print("=== GEMINI REVIEW (gemini flash vision) ===")
        t0 = time.time()
        try:
            from google import genai
            client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
            from google.genai import types
            content = [REVIEW_PROMPT.format(script=script_text[:12000])]
            for f in frame_files:
                t = f.split("_")[1].split(".")[0]
                b64 = _b64(os.path.join(args.frames, f))
                content.append(f"FRAME t={t}s (filename {f}):")
                content.append(types.Part.from_bytes(
                    data=base64.b64decode(b64), mime_type="image/jpeg"))
            out = None
            used_model = None
            for model in ["gemini-2.5-flash", "gemini-3.5-flash", "gemini-3-flash-preview"]:
                try:
                    resp = client.models.generate_content(model=model, contents=content)
                    out = resp.text
                    used_model = model
                    break
                except Exception as e:
                    print(f"  !! {model} failed: {str(e)[:120]}")
                    continue
            if out is None:
                print("  !! GEMINI: all models failed — skipping")
            else:
                review = _parse_json(out)
                review["_meta"] = {"provider": "gemini", "model": used_model, "elapsed_s": round(time.time() - t0, 1)}
                with open(os.path.join(args.outdir, "review_gemini.json"), "w") as f:
                    json.dump(review, f, indent=2)
                results["gemini"] = review
                print(f"  score {review.get('quality_score')}/100 (conf {review.get('confidence')})")
        except Exception as e:
            print(f"  !! GEMINI provider error: {str(e)[:150]} — skipping")

    if "openrouter" in args.providers:
        print("=== OPENROUTER REVIEW (free vision model) ===")
        # Generic OpenRouter reviewer: try the strongest free vision model first.
        or_models = [
            "google/gemma-4-31b-it:free",
            "google/gemma-4-26b-a4b-it:free",
            "nvidia/nemotron-nano-12b-v2-vl:free",
        ]
        t0 = time.time()
        out = None
        used_model = None
        for om in or_models:
            try:
                print(f"  trying {om}")
                out = _openrouter_chat(
                    [{"role": "user", "content": _frames_content(REVIEW_PROMPT.format(script=script_text[:12000]))}],
                    om,
                    attempts=4,
                )
                used_model = om
                break
            except Exception as e:
                print(f"  !! {om} gave up: {str(e)[:120]}")
        if out is None:
            print("  !! OPENROUTER: all free models exhausted — skipping")
        else:
            review = _parse_json(out)
            review["_meta"] = {"provider": "openrouter", "model": used_model, "elapsed_s": round(time.time() - t0, 1)}
            with open(os.path.join(args.outdir, "review_openrouter.json"), "w") as f:
                json.dump(review, f, indent=2)
            results["openrouter"] = review
            print(f"  score {review.get('quality_score')}/100 (conf {review.get('confidence')})")

    if "grok" in args.providers:
        print("=== GROK REVIEW (x-ai/grok-4.5 via OpenRouter) ===")
        content = [{"type": "text", "text": REVIEW_PROMPT.format(script=script_text[:12000])}]
        for f in frame_files:
            t = f.split("_")[1].split(".")[0]
            content.append({
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{_b64(os.path.join(args.frames, f))}"},
            })
        t0 = time.time()
        try:
            out = _openrouter_grok([{"role": "user", "content": content}])
        except Exception as e:
            print(f"  !! GROK failed: {str(e)[:150]} — skipping (leaving any prior review_grok.json)")
            out = None
        if out is not None:
            review = _parse_json(out)
            review["_meta"] = {"provider": "grok", "model": "x-ai/grok-4.5", "elapsed_s": round(time.time() - t0, 1)}
            with open(os.path.join(args.outdir, "review_grok.json"), "w") as f:
                json.dump(review, f, indent=2)
            results["grok"] = review
            print(f"  score {review.get('quality_score')}/100 (conf {review.get('confidence')})")

        # Frame descriptions for DeepSeek (visual transcript)
        desc_content = [{"type": "text", "text": FRAME_DESC_PROMPT}]
        for f in frame_files:
            desc_content.append({
                "type": "image_url",
                "image_url": {"url": f"data:image/jpeg;base64,{_b64(os.path.join(args.frames, f))}"},
            })
        try:
            desc_out = _openrouter_grok([{"role": "user", "content": desc_content}], json_mode=True, max_tokens=2500)
            descs = _parse_json(desc_out).get("frames", [])
            with open(os.path.join(args.outdir, "frame_descriptions.json"), "w") as f:
                json.dump(descs, f, indent=2)
            print(f"  frame descriptions: {len(descs)}")
        except Exception as e:
            # v19n.3: grok desc failure must not kill the batch — DeepSeek
            # can still run with a pre-existing frame_descriptions.json
            # (describe_frames.py) or an empty transcript.
            print(f"  !! frame descriptions failed ({str(e)[:100]}) — DeepSeek may fall back to existing transcript")

    if "deepseek" in args.providers:
        print("=== DEEPSEEK PRO REVIEW (deepseek-v4-pro) ===")
        desc_path = os.path.join(args.outdir, "frame_descriptions.json")
        if os.path.exists(desc_path):
            with open(desc_path) as f:
                descs = json.load(f)
        else:
            descs = []
        visual_transcript = "\n".join(f"[{d.get('t')}s] {d.get('desc')}" for d in descs)
        prompt = REVIEW_PROMPT.format(script=script_text[:12000])
        prompt += "\n\nVISUAL TRANSCRIPT (frame descriptions from sampled frames):\n" + visual_transcript
        if timeline_text:
            prompt += "\n\nSHOT TIMELINE:\n" + timeline_text[:8000]
        t0 = time.time()
        out = _deepseek_pro(prompt)
        review = _parse_json(out)
        review["_meta"] = {"provider": "deepseek", "model": "deepseek-v4-pro", "elapsed_s": round(time.time() - t0, 1)}
        with open(os.path.join(args.outdir, "review_deepseek_pro.json"), "w") as f:
            json.dump(review, f, indent=2)
        results["deepseek"] = review
        print(f"  score {review.get('quality_score')}/100 (conf {review.get('confidence')})")

    print("\n=== SUMMARY ===")
    for k, r in results.items():
        print(f"{k}: {r.get('quality_score')}/100 conf {r.get('confidence')}")
        for rec in r.get("prioritized_recommendations", [])[:8]:
            print(f"  [{rec.get('priority','?').upper()}][{rec.get('category','?')}] {rec.get('recommendation','')[:130]}")


if __name__ == "__main__":
    main()
